# Generated by Django 5.1.4 on 2025-05-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/')),
                ('image', models.ImageField(upload_to='videos/thumbnails/')),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('body_focus', models.CharField(choices=[('Total', 'Total Body'), ('Core', 'Core'), ('Upper', 'Upper Body'), ('Lower', 'Lower Body')], max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50)),
                ('equipment', models.JSONField(default=list)),
                ('structure', models.JSONField(default=list)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'video',
                'ordering': ['-created_at'],
            },
        ),
    ]
