# Generated by Django 5.2.1 on 2025-06-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_videocomplete_videolike_videosave'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomplete',
            name='calories_burned',
            field=models.IntegerField(default=0, help_text='Calories burned during this workout'),
        ),
    ]
