# Generated by Django 5.2.1 on 2025-06-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_videocomplete_calories_burned'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='calories',
            field=models.IntegerField(default=0, help_text='Calories burned for this workout'),
        ),
    ]
