# Generated by Django 5.2.1 on 2025-06-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocomplete',
            name='calories_burned',
        ),
        migrations.AlterField(
            model_name='video',
            name='calories',
            field=models.PositiveIntegerField(default=0, help_text='Estimated calories burned'),
        ),
    ]
