# Generated by Django 5.2.1 on 2025-06-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_remove_videocomplete_calories_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomplete',
            name='calories_burned',
            field=models.PositiveIntegerField(default=0, help_text='Calories burned from this video'),
        ),
    ]
