# Generated by Django 5.1.4 on 2025-05-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
