# Generated by Django 5.1.4 on 2025-04-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_analysis', '0001_create_processed_video_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedvideo',
            name='original_video',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='processedvideo',
            name='processed_video',
            field=models.FileField(upload_to='processed/'),
        ),
    ]
