# Generated by Django 5.1.4 on 2025-05-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_analysis', '0003_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
