# Generated by Django 5.1.4 on 2025-05-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_analysis', '0004_article_category_article_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.CharField(default='5 min read', max_length=20),
        ),
    ]
