# Generated by Django 5.1.4 on 2025-05-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_analysis', '0005_article_read_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='workout_article',
        ),
    ]
