# Generated by Django 5.1.4 on 2025-05-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_analysis', '0007_merge_article_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=200),
        ),
    ]
